CREATE TABLE AR_CustomerContact
(
    ARDivisionNo      varchar(2)  NOT NULL,
    CustomerNo        varchar(20) NOT NULL,
    ContactCode       varchar(10) NOT NULL,
    ContactName       varchar(50) DEFAULT NULL,
    AddressLine1      varchar(40) DEFAULT NULL,
    AddressLine2      varchar(40) DEFAULT NULL,
    AddressLine3      varchar(40) DEFAULT NULL,
    City              varchar(30) DEFAULT NULL,
    State             varchar(2)  DEFAULT NULL,
    ZipCode           varchar(10) DEFAULT NULL,
    CountryCode       varchar(3)  DEFAULT NULL,
    Salutation        varchar(10) DEFAULT NULL,
    ContactTitle      varchar(15) DEFAULT NULL,
    TelephoneNo1      varchar(20) DEFAULT NULL,
    TelephoneExt1     varchar(6)  DEFAULT NULL,
    TelephoneNo2      varchar(20) DEFAULT NULL,
    TelephoneExt2     varchar(6)  DEFAULT NULL,
    FaxNo             varchar(20) DEFAULT NULL,
    EmailAddress      varchar(50) DEFAULT NULL,
    ContactNotes      TEXT        DEFAULT NULL,
    EBMUserID         varchar(15) DEFAULT NULL,
    DateCreated       date        DEFAULT NULL,
    TimeCreated       varchar(8)  DEFAULT NULL,
    UserCreatedKey    varchar(10) DEFAULT NULL,
    DateUpdated       date        DEFAULT NULL,
    TimeUpdated       varchar(8)  DEFAULT NULL,
    UserUpdatedKey    varchar(10) DEFAULT NULL,
    TelephoneType1    varchar(1)  DEFAULT NULL,
    PrimaryTelephone1 varchar(1)  DEFAULT NULL,
    TelephoneType2    varchar(1)  DEFAULT NULL,
    PrimaryTelephone2 varchar(1)  DEFAULT NULL,
    EncryptedVals     TEXT        DEFAULT NULL,
    PRIMARY KEY (`ARDivisionNo`, `CustomerNo`, `ContactCode`)
)
