CREATE TABLE AR_Customer
(
    ARDivisionNo               varchar(2)  NOT NULL,
    CustomerNo                 varchar(20) NOT NULL,
    CustomerName               varchar(50)    DEFAULT NULL,
    AddressLine1               varchar(40)    DEFAULT NULL,
    AddressLine2               varchar(40)    DEFAULT NULL,
    AddressLine3               varchar(40)    DEFAULT NULL,
    City                       varchar(30)    DEFAULT NULL,
    State                      varchar(2)     DEFAULT NULL,
    ZipCode                    varchar(10)    DEFAULT NULL,
    CountryCode                varchar(3)     DEFAULT NULL,
    TelephoneNo                varchar(20)    DEFAULT NULL,
    TelephoneExt               varchar(6)     DEFAULT NULL,
    FaxNo                      varchar(20)    DEFAULT NULL,
    EmailAddress               varchar(250)   DEFAULT NULL,
    URLAddress                 varchar(50)    DEFAULT NULL,
    EBMEnabled                 varchar(1)     DEFAULT NULL,
    EBMConsumerUserID          varchar(15)    DEFAULT NULL,
    BatchFax                   varchar(1)     DEFAULT NULL,
    DefaultCreditCardPmtType   varchar(5)     DEFAULT NULL,
    ContactCode                varchar(10)    DEFAULT NULL,
    ShipMethod                 varchar(15)    DEFAULT NULL,
    TaxSchedule                varchar(9)     DEFAULT NULL,
    TaxExemptNo                varchar(15)    DEFAULT NULL,
    TermsCode                  varchar(2)     DEFAULT NULL,
    SalespersonDivisionNo      varchar(2)     DEFAULT NULL,
    SalespersonNo              varchar(4)     DEFAULT NULL,
    Comment                    varchar(30)    DEFAULT NULL,
    SortField                  varchar(10)    DEFAULT NULL,
    TemporaryCustomer          varchar(1)     DEFAULT NULL,
    OpenItemCustomer           varchar(1)     DEFAULT NULL,
    ResidentialAddress         varchar(1)     DEFAULT NULL,
    StatementCycle             varchar(1)     DEFAULT NULL,
    PrintDunningMessage        varchar(1)     DEFAULT NULL,
    CustomerType               varchar(4)     DEFAULT NULL,
    PriceLevel                 varchar(1)     DEFAULT NULL,
    DateLastActivity           date           DEFAULT NULL,
    DateLastPayment            date           DEFAULT NULL,
    DateLastStatement          date           DEFAULT NULL,
    DateLastFinanceChrg        date           DEFAULT NULL,
    DateLastAging              date           DEFAULT NULL,
    DefaultItemCode            varchar(30)    DEFAULT NULL,
    CreditHold                 varchar(1)     DEFAULT NULL,
    PrimaryShipToCode          varchar(4)     DEFAULT NULL,
    DateEstablished            date           DEFAULT NULL,
    DefaultPaymentType         varchar(5)     DEFAULT NULL,
    EmailStatements            varchar(1)     DEFAULT NULL,
    NumberOfInvToUseInCalc     decimal(2, 0)  DEFAULT NULL,
    AvgDaysPaymentInvoice      decimal(3, 0)  DEFAULT NULL,
    AvgDaysOverDue             decimal(3, 0)  DEFAULT NULL,
    CustomerDiscountRate       decimal(12, 3) DEFAULT NULL,
    ServiceChargeRate          decimal(12, 3) DEFAULT NULL,
    CreditLimit                decimal(13, 2) DEFAULT NULL,
    LastPaymentAmt             decimal(13, 2) DEFAULT NULL,
    HighestStmntBalance        decimal(13, 2) DEFAULT NULL,
    UnpaidServiceChrg          decimal(13, 2) DEFAULT NULL,
    BalanceForward             decimal(13, 2) DEFAULT NULL,
    CurrentBalance             decimal(13, 2) DEFAULT NULL,
    AgingCategory1             decimal(13, 2) DEFAULT NULL,
    AgingCategory2             decimal(13, 2) DEFAULT NULL,
    AgingCategory3             decimal(13, 2) DEFAULT NULL,
    AgingCategory4             decimal(13, 2) DEFAULT NULL,
    OpenOrderAmt               decimal(13, 2) DEFAULT NULL,
    RetentionCurrent           decimal(13, 2) DEFAULT NULL,
    RetentionAging1            decimal(13, 2) DEFAULT NULL,
    RetentionAging2            decimal(13, 2) DEFAULT NULL,
    RetentionAging3            decimal(13, 2) DEFAULT NULL,
    RetentionAging4            decimal(13, 2) DEFAULT NULL,
    DateCreated                date           DEFAULT NULL,
    TimeCreated                varchar(8)     DEFAULT NULL,
    UserCreatedKey             varchar(10)    DEFAULT NULL,
    DateUpdated                date           DEFAULT NULL,
    TimeUpdated                varchar(8)     DEFAULT NULL,
    UserUpdatedKey             varchar(10)    DEFAULT NULL,
    UDF_SHIP_SPEC              varchar(1)     DEFAULT NULL,
    UDF_CHUMS_ACCT             varchar(8)     DEFAULT NULL,
    UDF_CVENDOR                varchar(25)    DEFAULT NULL,
    UDF_INTERNETRESELLER       varchar(1)     DEFAULT NULL,
    UDF_RESELLER               varchar(1)     DEFAULT NULL,
    SalespersonDivisionNo2     varchar(2)     DEFAULT NULL,
    SalespersonNo2             varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo3     varchar(2)     DEFAULT NULL,
    SalespersonNo3             varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo4     varchar(2)     DEFAULT NULL,
    SalespersonNo4             varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo5     varchar(2)     DEFAULT NULL,
    SalespersonNo5             varchar(4)     DEFAULT NULL,
    CustomerStatus             varchar(1)     DEFAULT NULL,
    InactiveReasonCode         varchar(5)     DEFAULT NULL,
    DefaultCostCode            varchar(9)     DEFAULT NULL,
    DefaultCostType            varchar(1)     DEFAULT NULL,
    CreditCardGUID             varchar(32)    DEFAULT NULL,
    SplitCommRate2             decimal(8, 3)  DEFAULT NULL,
    SplitCommRate3             decimal(8, 3)  DEFAULT NULL,
    SplitCommRate4             decimal(8, 3)  DEFAULT NULL,
    SplitCommRate5             decimal(8, 3)  DEFAULT NULL,
    UseSageCloudForInvPrinting varchar(1)     DEFAULT NULL,
    TelephoneType              varchar(1)     DEFAULT NULL,
    EInvoicePayments           varchar(1)     DEFAULT NULL,
    EInvoiceContactId          varchar(24)    DEFAULT NULL,
    PIIEncryptedDate           date           DEFAULT NULL,
    EncryptedVals              TEXT           DEFAULT NULL,
    PRIMARY KEY (`ARDivisionNo`, `CustomerNo`)
)
