CREATE TABLE AR_CashReceiptsHistory
(
    BankCode                      varchar(1)  NOT NULL,
    DepositDate                   date        NOT NULL,
    DepositNo                     varchar(5)  NOT NULL,
    DepositType                   varchar(1)  NOT NULL,
    ARDivisionNo                  varchar(2)  NOT NULL,
    CustomerNo                    varchar(20) NOT NULL,
    CheckNo                       varchar(10) NOT NULL,
    SequenceNo                    varchar(6)  NOT NULL,
    PostingDate                   date           DEFAULT NULL,
    CustomerName                  varchar(50)    DEFAULT NULL,
    OpenItemCustomer              varchar(1)     DEFAULT NULL,
    TransactionType               varchar(2)     DEFAULT NULL,
    InvoiceNo                     varchar(7)     DEFAULT NULL,
    InvoiceType                   varchar(2)     DEFAULT NULL,
    AccountKey                    varchar(9)     DEFAULT NULL,
    DepositDesc                   varchar(30)    DEFAULT NULL,
    BatchNo                       varchar(5)     DEFAULT NULL,
    Last4UnencryptedCreditCardNos varchar(4)     DEFAULT NULL,
    ExpirationDateYear            varchar(4)     DEFAULT NULL,
    ExpirationDateMonth           varchar(2)     DEFAULT NULL,
    CorporateCustIDPurchOrder     varchar(17)    DEFAULT NULL,
    CorporateTaxOverrd            varchar(1)     DEFAULT NULL,
    CardholderName                varchar(50)    DEFAULT NULL,
    CreditCardTransactionID       varchar(15)    DEFAULT NULL,
    CreditCardAuthorizationNo     varchar(16)    DEFAULT NULL,
    AuthorizationDate             date           DEFAULT NULL,
    AuthorizationTime             varchar(8)     DEFAULT NULL,
    AVSCity                       varchar(30)    DEFAULT NULL,
    AVSState                      varchar(2)     DEFAULT NULL,
    AVSZipCode                    varchar(10)    DEFAULT NULL,
    CreditCardComment             varchar(30)    DEFAULT NULL,
    Comment                       TEXT           DEFAULT NULL,
    CashAmountApplied             decimal(12, 2) DEFAULT NULL,
    DiscountAmountApplied         decimal(12, 2) DEFAULT NULL,
    InvoiceBalance                decimal(13, 2) DEFAULT NULL,
    CorporateSalesTax             decimal(11, 2) DEFAULT NULL,
    DateUpdated                   date           DEFAULT NULL,
    TimeUpdated                   varchar(8)     DEFAULT NULL,
    UserUpdatedKey                varchar(10)    DEFAULT NULL,
    CreditCardEntryNo             varchar(6)  NOT NULL,
    SoldToDivisionNo              varchar(2)     DEFAULT NULL,
    SoldToCustomerNo              varchar(20)    DEFAULT NULL,
    PaymentType                   varchar(5)     DEFAULT NULL,
    CreditCardID                  varchar(10)    DEFAULT NULL,
    CardType                      varchar(1)     DEFAULT NULL,
    BankAccountType               varchar(1)     DEFAULT NULL,
    Last4BankRoutingNos           varchar(4)     DEFAULT NULL,
    Last4BankAccountNos           varchar(4)     DEFAULT NULL,
    BankName                      varchar(30)    DEFAULT NULL,
    AVSAddressLine1               varchar(40)    DEFAULT NULL,
    AVSAddressLine2               varchar(40)    DEFAULT NULL,
    AVSCountryCode                varchar(3)     DEFAULT NULL,
    CreditCardEmailAddress        varchar(250)   DEFAULT NULL,
    DateCreated                   date           DEFAULT NULL,
    TimeCreated                   varchar(8)     DEFAULT NULL,
    UserCreatedKey                varchar(10)    DEFAULT NULL,
    AVSAddressLine3               varchar(40)    DEFAULT NULL,
    EInvoiceTransactionId         varchar(24)    DEFAULT NULL,
    EncryptedVals                 TEXT           DEFAULT NULL,
    PRIMARY KEY (`BankCode`, `DepositDate`, `DepositNo`, `DepositType`, `ARDivisionNo`, `CustomerNo`,
                 `CreditCardEntryNo`, `CheckNo`, `SequenceNo`)
);
CREATE INDEX KEY0 on AR_CashReceiptsHistory (BankCode, DepositDate, DepositNo, DepositType, ARDivisionNo, CustomerNo,
                                             CreditCardEntryNo, CheckNo, SequenceNo);
CREATE INDEX KEY1 on AR_CashReceiptsHistory (ARDivisionNo, CustomerNo, InvoiceNo);
CREATE INDEX KEY2 on AR_CashReceiptsHistory (DepositDate DESC, BankCode, DepositNo, DepositType, ARDivisionNo,
                                             CustomerNo, CreditCardEntryNo, CheckNo, SequenceNo);
CREATE INDEX KEY3 on AR_CashReceiptsHistory (DepositDate, BankCode, DepositNo, DepositType, ARDivisionNo, CustomerNo,
                                             CreditCardEntryNo, CheckNo, SequenceNo);
CREATE INDEX KEY4 on AR_CashReceiptsHistory (CheckNo, DepositDate, BankCode, DepositNo, DepositType, ARDivisionNo,
                                             CustomerNo, SequenceNo);
CREATE INDEX KEY5 on AR_CashReceiptsHistory (ExpirationDateYear, ExpirationDateMonth, BankCode, DepositDate, DepositNo,
                                             ARDivisionNo, CustomerNo, CreditCardEntryNo, CheckNo, SequenceNo);
CREATE INDEX KEY6 on AR_CashReceiptsHistory (EInvoiceTransactionId, BankCode, DepositDate, DepositNo, DepositType,
                                             ARDivisionNo, CustomerNo, CreditCardEntryNo, CheckNo, SequenceNo);
