CREATE TABLE IF NOT EXISTS AR_InvoiceHistoryHeader
(
    InvoiceNo                    varchar(7) NOT NULL,
    HeaderSeqNo                  varchar(6) NOT NULL,
    ModuleCode                   varchar(3)     DEFAULT NULL,
    InvoiceType                  varchar(2)     DEFAULT NULL,
    InvoiceDate                  date           DEFAULT NULL,
    TransactionDate              date           DEFAULT NULL,
    ARDivisionNo                 varchar(2)     DEFAULT NULL,
    CustomerNo                   varchar(20)    DEFAULT NULL,
    TermsCode                    varchar(2)     DEFAULT NULL,
    TaxSchedule                  varchar(9)     DEFAULT NULL,
    TaxExemptNo                  varchar(15)    DEFAULT NULL,
    SalespersonDivisionNo        varchar(2)     DEFAULT NULL,
    SalespersonNo                varchar(4)     DEFAULT NULL,
    CustomerPONo                 varchar(30)    DEFAULT NULL,
    ApplyToInvoiceNo             varchar(7)     DEFAULT NULL,
    Comment                      varchar(30)    DEFAULT NULL,
    RepetitiveInvoiceRefNo       varchar(4)     DEFAULT NULL,
    JobNo                        varchar(7)     DEFAULT NULL,
    InvoiceDueDate               date           DEFAULT NULL,
    DiscountDueDate              date           DEFAULT NULL,
    SourceJournal                varchar(2)     DEFAULT NULL,
    JournalNoGLBatchNo           varchar(6)     DEFAULT NULL,
    BatchFax                     varchar(1)     DEFAULT NULL,
    FaxNo                        varchar(20)    DEFAULT NULL,
    ShippingInvoice              varchar(1)     DEFAULT NULL,
    SalesOrderNo                 varchar(7)     DEFAULT NULL,
    OrderType                    varchar(1)     DEFAULT NULL,
    OrderDate                    date           DEFAULT NULL,
    BillToName                   varchar(50)    DEFAULT NULL,
    BillToAddress1               varchar(40)    DEFAULT NULL,
    BillToAddress2               varchar(40)    DEFAULT NULL,
    BillToAddress3               varchar(40)    DEFAULT NULL,
    BillToCity                   varchar(30)    DEFAULT NULL,
    BillToState                  varchar(2)     DEFAULT NULL,
    BillToZipCode                varchar(10)    DEFAULT NULL,
    BillToCountryCode            varchar(3)     DEFAULT NULL,
    ShipToCode                   varchar(4)     DEFAULT NULL,
    ShipToName                   varchar(50)    DEFAULT NULL,
    ShipToAddress1               varchar(40)    DEFAULT NULL,
    ShipToAddress2               varchar(40)    DEFAULT NULL,
    ShipToAddress3               varchar(40)    DEFAULT NULL,
    ShipToCity                   varchar(30)    DEFAULT NULL,
    ShipToState                  varchar(2)     DEFAULT NULL,
    ShipToZipCode                varchar(10)    DEFAULT NULL,
    ShipToCountryCode            varchar(3)     DEFAULT NULL,
    ShipDate                     date           DEFAULT NULL,
    ShipVia                      varchar(15)    DEFAULT NULL,
    ShipZone                     varchar(5)     DEFAULT NULL,
    FOB                          varchar(15)    DEFAULT NULL,
    ConfirmTo                    varchar(50)    DEFAULT NULL,
    CheckNoForDeposit            varchar(10)    DEFAULT NULL,
    SplitCommissions             varchar(1)     DEFAULT NULL,
    SalespersonDivisionNo2       varchar(2)     DEFAULT NULL,
    SalespersonNo2               varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo3       varchar(2)     DEFAULT NULL,
    SalespersonNo3               varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo4       varchar(2)     DEFAULT NULL,
    SalespersonNo4               varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo5       varchar(2)     DEFAULT NULL,
    SalespersonNo5               varchar(4)     DEFAULT NULL,
    PaymentType                  varchar(5)     DEFAULT NULL,
    PaymentTypeCategory          varchar(1)     DEFAULT NULL,
    OtherPaymentTypeRefNo        varchar(24)    DEFAULT NULL,
    RMANo                        varchar(7)     DEFAULT NULL,
    EBMSubmissionType            varchar(1)     DEFAULT NULL,
    EBMUserIDSubmittingThisOrder varchar(15)    DEFAULT NULL,
    EBMUserType                  varchar(1)     DEFAULT NULL,
    ShipperID                    varchar(3)     DEFAULT NULL,
    UserKey                      varchar(10)    DEFAULT NULL,
    WarehouseCode                varchar(3)     DEFAULT NULL,
    ShipWeight                   varchar(5)     DEFAULT NULL,
    ResidentialAddress           varchar(1)     DEFAULT NULL,
    EmailAddress                 varchar(250)   DEFAULT NULL,
    TaxableSalesAmt              decimal(12, 2) DEFAULT NULL,
    NonTaxableSalesAmt           decimal(12, 2) DEFAULT NULL,
    FreightAmt                   decimal(11, 2) DEFAULT NULL,
    SalesTaxAmt                  decimal(11, 2) DEFAULT NULL,
    CostOfSalesAmt               decimal(12, 2) DEFAULT NULL,
    AmountSubjectToDiscount      decimal(12, 2) DEFAULT NULL,
    DiscountRate                 decimal(8, 3)  DEFAULT NULL,
    DiscountAmt                  decimal(11, 2) DEFAULT NULL,
    SalesSubjectToComm           decimal(12, 2) DEFAULT NULL,
    CostSubjectToComm            decimal(12, 2) DEFAULT NULL,
    CommissionRate               decimal(8, 3)  DEFAULT NULL,
    CommissionAmt                decimal(12, 2) DEFAULT NULL,
    SplitCommRate2               decimal(8, 3)  DEFAULT NULL,
    SplitCommRate3               decimal(8, 3)  DEFAULT NULL,
    SplitCommRate4               decimal(8, 3)  DEFAULT NULL,
    SplitCommRate5               decimal(8, 3)  DEFAULT NULL,
    DepositAmt                   decimal(12, 2) DEFAULT NULL,
    Weight                       decimal(11, 2) DEFAULT NULL,
    RetentionAmt                 decimal(12, 2) DEFAULT NULL,
    NumberOfPackages             decimal(5, 0)  DEFAULT NULL,
    DateUpdated                  date           DEFAULT NULL,
    TimeUpdated                  varchar(8)     DEFAULT NULL,
    UserUpdatedKey               varchar(10)    DEFAULT NULL,
    UDF_MFP_NAME                 varchar(20)    DEFAULT NULL,
    UDF_MFP_NUMBER               decimal(7, 0)  DEFAULT NULL,
    UDF_PROGRAMCOUNT             varchar(10)    DEFAULT NULL,
    UDF_PROGRAMID                varchar(10)    DEFAULT NULL,
    UDF_MEMO                     TEXT           DEFAULT NULL,
    CRMUserID                    varchar(11)    DEFAULT NULL,
    CRMCompanyID                 varchar(11)    DEFAULT NULL,
    CRMPersonID                  varchar(11)    DEFAULT NULL,
    CRMOpportunityID             varchar(11)    DEFAULT NULL,
    BillToDivisionNo             varchar(2)     DEFAULT NULL,
    BillToCustomerNo             varchar(20)    DEFAULT NULL,
    DateCreated                  date           DEFAULT NULL,
    TimeCreated                  varchar(8)     DEFAULT NULL,
    UserCreatedKey               varchar(10)    DEFAULT NULL,
    MultipleSalesOrdersApplied   varchar(1)     DEFAULT NULL,
    MultipleCustomerPONos        varchar(1)     DEFAULT NULL,
    MultipleDepositsApplied      varchar(1)     DEFAULT NULL,
    UDF_ASN_NUM                  varchar(9)     DEFAULT NULL,
    UDF_BOL_NUMBER               varchar(30)    DEFAULT NULL,
    UDF_BT                       varchar(20)    DEFAULT NULL,
    UDF_CANCEL_DATE              date           DEFAULT NULL,
    UDF_CUST_ORD_NO              varchar(30)    DEFAULT NULL,
    UDF_DC                       varchar(4)     DEFAULT NULL,
    UDF_DEPT                     varchar(15)    DEFAULT NULL,
    UDF_DEPT_NAME                varchar(30)    DEFAULT NULL,
    UDF_DIV_REGION               varchar(30)    DEFAULT NULL,
    UDF_LETETER_CR               varchar(30)    DEFAULT NULL,
    UDF_MR                       varchar(30)    DEFAULT NULL,
    UDF_PROMO_DEAL               varchar(30)    DEFAULT NULL,
    UDF_PRO_NUM                  varchar(30)    DEFAULT NULL,
    UDF_REQUESTED_DELIVERY       date           DEFAULT NULL,
    UDF_SCAC                     varchar(30)    DEFAULT NULL,
    UDF_ST                       varchar(20)    DEFAULT NULL,
    UDF_ST_PER01                 varchar(3)     DEFAULT NULL,
    UDF_ST_PER02                 varchar(35)    DEFAULT NULL,
    UDF_ST_PER04_TE              varchar(15)    DEFAULT NULL,
    UDF_ST_PER06_EM              varchar(50)    DEFAULT NULL,
    UDF_ST_PER08_FX              varchar(15)    DEFAULT NULL,
    UDF_TOTAL_CASES              decimal(9, 2)  DEFAULT NULL,
    UDF_TOTAL_EACHES             decimal(9, 2)  DEFAULT NULL,
    UDF_TRAILER_NUM              varchar(20)    DEFAULT NULL,
    UDF_VENDOR_NO                varchar(30)    DEFAULT NULL,
    UDF_VOLUME                   decimal(9, 2)  DEFAULT NULL,
    UDF_Z7                       varchar(20)    DEFAULT NULL,
    EInvoiceId                   varchar(24)    DEFAULT NULL,
    EncryptedVals                TEXT           DEFAULT NULL,
    PRIMARY KEY (`InvoiceNo`, `HeaderSeqNo`)
)
