CREATE TABLE AR_InvoiceHistoryDetail
(
    InvoiceNo                 varchar(7) NOT NULL,
    HeaderSeqNo               varchar(6) NOT NULL,
    DetailSeqNo               varchar(6) NOT NULL,
    ItemCode                  varchar(30)    DEFAULT NULL,
    ItemType                  varchar(1)     DEFAULT NULL,
    ItemCodeDesc              varchar(30)    DEFAULT NULL,
    ExtendedDescriptionKey    varchar(10)    DEFAULT NULL,
    SalesAcctKey              varchar(9)     DEFAULT NULL,
    CostOfGoodsSoldAcctKey    varchar(9)     DEFAULT NULL,
    InventoryAcctKey          varchar(9)     DEFAULT NULL,
    UnitOfMeasure             varchar(4)     DEFAULT NULL,
    SubjectToExemption        varchar(1)     DEFAULT NULL,
    Commissionable            varchar(1)     DEFAULT NULL,
    TaxClass                  varchar(2)     DEFAULT NULL,
    Discount                  varchar(1)     DEFAULT NULL,
    DropShip                  varchar(1)     DEFAULT NULL,
    WarehouseCode             varchar(3)     DEFAULT NULL,
    PriceLevel                varchar(1)     DEFAULT NULL,
    ProductLine               varchar(4)     DEFAULT NULL,
    Valuation                 varchar(1)     DEFAULT NULL,
    PriceOverridden           varchar(1)     DEFAULT NULL,
    OrderWarehouse            varchar(3)     DEFAULT NULL,
    Revision                  varchar(3)     DEFAULT NULL,
    BillOption1               varchar(2)     DEFAULT NULL,
    BillOption2               varchar(2)     DEFAULT NULL,
    BillOption3               varchar(2)     DEFAULT NULL,
    BillOption4               varchar(2)     DEFAULT NULL,
    BillOption5               varchar(2)     DEFAULT NULL,
    BillOption6               varchar(2)     DEFAULT NULL,
    BillOption7               varchar(2)     DEFAULT NULL,
    BillOption8               varchar(2)     DEFAULT NULL,
    BillOption9               varchar(2)     DEFAULT NULL,
    KitItem                   varchar(1)     DEFAULT NULL,
    ExplodedKitItem           varchar(1)     DEFAULT NULL,
    SkipPrintCompLine         varchar(1)     DEFAULT NULL,
    StandardKitBill           varchar(1)     DEFAULT NULL,
    AliasItemNo               varchar(30)    DEFAULT NULL,
    CustomerAction            varchar(1)     DEFAULT NULL,
    ItemAction                varchar(1)     DEFAULT NULL,
    WarrantyCode              varchar(10)    DEFAULT NULL,
    ExpirationDate            date           DEFAULT NULL,
    ExpirationOverridden      varchar(1)     DEFAULT NULL,
    CostCode                  varchar(9)     DEFAULT NULL,
    CostType                  varchar(1)     DEFAULT NULL,
    CommentText               TEXT           DEFAULT NULL,
    PromiseDate               date           DEFAULT NULL,
    QuantityShipped           decimal(15, 6) DEFAULT NULL,
    QuantityOrdered           decimal(15, 6) DEFAULT NULL,
    QuantityBackordered       decimal(15, 6) DEFAULT NULL,
    UnitPrice                 decimal(15, 6) DEFAULT NULL,
    UnitCost                  decimal(15, 6) DEFAULT NULL,
    UnitOfMeasureConvFactor   decimal(11, 4) DEFAULT NULL,
    CommissionAmt             decimal(12, 2) DEFAULT NULL,
    LineDiscountPercent       decimal(8, 3)  DEFAULT NULL,
    QuantityPerBill           decimal(15, 6) DEFAULT NULL,
    ExtensionAmt              decimal(11, 2) DEFAULT NULL,
    APDivisionNo              varchar(2)     DEFAULT NULL,
    VendorNo                  varchar(7)     DEFAULT NULL,
    PurchaseOrderNo           varchar(7)     DEFAULT NULL,
    PurchaseOrderRequiredDate date           DEFAULT NULL,
    CommodityCode             varchar(12)    DEFAULT NULL,
    AlternateTaxIdentifier    varchar(15)    DEFAULT NULL,
    TaxTypeApplied            varchar(4)     DEFAULT NULL,
    NetGrossIndicator         varchar(1)     DEFAULT NULL,
    DebitCreditIndicator      varchar(1)     DEFAULT NULL,
    TaxAmt                    decimal(11, 2) DEFAULT NULL,
    TaxRate                   decimal(10, 6) DEFAULT NULL,
    AppliedSalesOrderNo       varchar(7)     DEFAULT NULL,
    AppliedCustomerPONo       varchar(30)    DEFAULT NULL,
    UDF_BO                    varchar(30)    DEFAULT NULL,
    UDF_IN                    varchar(30)    DEFAULT NULL,
    UDF_IZ                    varchar(30)    DEFAULT NULL,
    UDF_ND                    varchar(30)    DEFAULT NULL,
    UDF_PO101                 varchar(20)    DEFAULT NULL,
    UDF_PO401                 decimal(9, 2)  DEFAULT NULL,
    UDF_PO402                 decimal(9, 2)  DEFAULT NULL,
    UDF_PO414                 decimal(9, 2)  DEFAULT NULL,
    UDF_RETAIL_PRICE          decimal(9, 2)  DEFAULT NULL,
    UDF_SKU                   varchar(30)    DEFAULT NULL,
    UDF_UA                    varchar(30)    DEFAULT NULL,
    UDF_UK                    varchar(30)    DEFAULT NULL,
    UDF_UM                    varchar(2)     DEFAULT NULL,
    UDF_UPC                   varchar(30)    DEFAULT NULL,
    UDF_VA                    varchar(30)    DEFAULT NULL,
    EncryptedVals             varchar(64)    DEFAULT NULL,
    PRIMARY KEY (`InvoiceNo`, `HeaderSeqNo`, `DetailSeqNo`)
);
CREATE INDEX KEY0 on AR_InvoiceHistoryDetail (InvoiceNo, HeaderSeqNo, DetailSeqNo);
CREATE INDEX KEY1 on AR_InvoiceHistoryDetail (ExtendedDescriptionKey, InvoiceNo, HeaderSeqNo, DetailSeqNo);
CREATE INDEX KEY2 on AR_InvoiceHistoryDetail (APDivisionNo, VendorNo, InvoiceNo, HeaderSeqNo, DetailSeqNo);
CREATE INDEX KEY3 on AR_InvoiceHistoryDetail (AppliedSalesOrderNo, InvoiceNo, HeaderSeqNo, DetailSeqNo);
CREATE INDEX KEY4 on AR_InvoiceHistoryDetail (InvoiceNo, HeaderSeqNo, AppliedSalesOrderNo, DetailSeqNo);
CREATE INDEX KEY5 on AR_InvoiceHistoryDetail (ItemCode, InvoiceNo, HeaderSeqNo, DetailSeqNo);
CREATE INDEX KEY6 on AR_InvoiceHistoryDetail (AppliedCustomerPONo, InvoiceNo, HeaderSeqNo, DetailSeqNo);
