CREATE TABLE AR_OpenInvoice
(
    ARDivisionNo               varchar(2)  NOT NULL,
    CustomerNo                 varchar(20) NOT NULL,
    InvoiceNo                  varchar(7)  NOT NULL,
    InvoiceType                varchar(2)  NOT NULL,
    InvoiceDate                date           DEFAULT NULL,
    InvoiceDueDate             date           DEFAULT NULL,
    InvoiceDiscountDate        date           DEFAULT NULL,
    InvoiceHistoryHeaderSeqNo  varchar(6)     DEFAULT NULL,
    PostingDate                date           DEFAULT NULL,
    TermsCode                  varchar(2)     DEFAULT NULL,
    TaxSchedule                varchar(9)     DEFAULT NULL,
    SalespersonDivisionNo      varchar(2)     DEFAULT NULL,
    SalespersonNo              varchar(4)     DEFAULT NULL,
    SplitCommissionFlag        varchar(1)     DEFAULT NULL,
    Comment                    varchar(30)    DEFAULT NULL,
    CreditMemoInvoiceReference varchar(7)     DEFAULT NULL,
    JobNo                      varchar(7)     DEFAULT NULL,
    CustomerPONo               varchar(30)    DEFAULT NULL,
    PostingReference           varchar(14)    DEFAULT NULL,
    CheckNo                    varchar(10)    DEFAULT NULL,
    CommissionRate             decimal(8, 3)  DEFAULT NULL,
    TaxableAmt                 decimal(13, 2) DEFAULT NULL,
    NonTaxableAmt              decimal(13, 2) DEFAULT NULL,
    FreightAmt                 decimal(12, 2) DEFAULT NULL,
    SalesTaxAmt                decimal(12, 2) DEFAULT NULL,
    CostOfSalesAmt             decimal(13, 2) DEFAULT NULL,
    SalesSubjectToComm         decimal(13, 2) DEFAULT NULL,
    CostSubjectToComm          decimal(13, 2) DEFAULT NULL,
    CommissionAmt              decimal(12, 2) DEFAULT NULL,
    DiscountAmt                decimal(13, 2) DEFAULT NULL,
    PaymentsToday              decimal(13, 2) DEFAULT NULL,
    Balance                    decimal(13, 2) DEFAULT NULL,
    RetentionAmt               decimal(13, 2) DEFAULT NULL,
    DateUpdated                date           DEFAULT NULL,
    TimeUpdated                varchar(8)     DEFAULT NULL,
    UserUpdatedKey             varchar(10)    DEFAULT NULL,
    SoldToDivisionNo           varchar(2)     DEFAULT NULL,
    SoldToCustomerNo           varchar(20)    DEFAULT NULL,
    DateCreated                date           DEFAULT NULL,
    TimeCreated                varchar(8)     DEFAULT NULL,
    UserCreatedKey             varchar(10)    DEFAULT NULL,
    EInvoiceId                 varchar(24)    DEFAULT NULL,
    PRIMARY KEY (`ARDivisionNo`, `CustomerNo`, `InvoiceNo`, `InvoiceType`)
)
