CREATE TABLE PO_PurchaseOrderHeader
(
    PurchaseOrderNo        varchar(7) NOT NULL,
    PurchaseOrderDate      date           DEFAULT NULL,
    OrderType              varchar(1)     DEFAULT NULL,
    MasterRepeatingOrderNo varchar(7)     DEFAULT NULL,
    RequiredExpireDate     date           DEFAULT NULL,
    APDivisionNo           varchar(2)     DEFAULT NULL,
    VendorNo               varchar(7)     DEFAULT NULL,
    PurchaseName           varchar(50)    DEFAULT NULL,
    PurchaseAddress1       varchar(40)    DEFAULT NULL,
    PurchaseAddress2       varchar(40)    DEFAULT NULL,
    PurchaseAddress3       varchar(40)    DEFAULT NULL,
    PurchaseCity           varchar(30)    DEFAULT NULL,
    PurchaseState          varchar(2)     DEFAULT NULL,
    PurchaseZipCode        varchar(10)    DEFAULT NULL,
    PurchaseCountryCode    varchar(3)     DEFAULT NULL,
    PurchaseAddressCode    varchar(4)     DEFAULT NULL,
    ShipToCode             varchar(4)     DEFAULT NULL,
    ShipToName             varchar(50)    DEFAULT NULL,
    ShipToAddress1         varchar(40)    DEFAULT NULL,
    ShipToAddress2         varchar(40)    DEFAULT NULL,
    ShipToAddress3         varchar(40)    DEFAULT NULL,
    ShipToCity             varchar(30)    DEFAULT NULL,
    ShipToState            varchar(2)     DEFAULT NULL,
    ShipToZipCode          varchar(10)    DEFAULT NULL,
    ShipToCountryCode      varchar(3)     DEFAULT NULL,
    OrderStatus            varchar(1)     DEFAULT NULL,
    UseTax                 varchar(1)     DEFAULT NULL,
    PrintPurchaseOrders    varchar(1)     DEFAULT NULL,
    OnHold                 varchar(1)     DEFAULT NULL,
    BatchFax               varchar(1)     DEFAULT NULL,
    CompletionDate         date           DEFAULT NULL,
    ShipVia                varchar(15)    DEFAULT NULL,
    FOB                    varchar(15)    DEFAULT NULL,
    WarehouseCode          varchar(3)     DEFAULT NULL,
    ConfirmTo              varchar(50)    DEFAULT NULL,
    Comment                varchar(30)    DEFAULT NULL,
    ARDivisionNo           varchar(2)     DEFAULT NULL,
    CustomerNo             varchar(20)    DEFAULT NULL,
    TermsCode              varchar(2)     DEFAULT NULL,
    LastInvoiceDate        date           DEFAULT NULL,
    LastInvoiceNo          varchar(20)    DEFAULT NULL,
    Form1099               varchar(1)     DEFAULT NULL,
    Box1099                varchar(3)     DEFAULT NULL,
    LastReceiptDate        date           DEFAULT NULL,
    LastIssueDate          date           DEFAULT NULL,
    LastReceiptNo          varchar(7)     DEFAULT NULL,
    LastIssueNo            varchar(7)     DEFAULT NULL,
    PrepaidCheckNo         varchar(10)    DEFAULT NULL,
    FaxNo                  varchar(20)    DEFAULT NULL,
    TaxSchedule            varchar(9)     DEFAULT NULL,
    InvalidTaxCalc         varchar(1)     DEFAULT NULL,
    PrepaidAmt             decimal(12, 2) DEFAULT NULL,
    TaxableAmt             decimal(12, 2) DEFAULT NULL,
    NonTaxableAmt          decimal(12, 2) DEFAULT NULL,
    SalesTaxAmt            decimal(11, 2) DEFAULT NULL,
    FreightAmt             decimal(11, 2) DEFAULT NULL,
    PrepaidFreightAmt      decimal(11, 2) DEFAULT NULL,
    InvoicedAmt            decimal(12, 2) DEFAULT NULL,
    ReceivedAmt            decimal(12, 2) DEFAULT NULL,
    FreightSalesTaxInvAmt  decimal(12, 2) DEFAULT NULL,
    BackOrderLostAmt       decimal(12, 2) DEFAULT NULL,
    DateCreated            date           DEFAULT NULL,
    TimeCreated            varchar(8)     DEFAULT NULL,
    UserCreatedKey         varchar(10)    DEFAULT NULL,
    DateUpdated            date           DEFAULT NULL,
    TimeUpdated            varchar(8)     DEFAULT NULL,
    UserUpdatedKey         varchar(10)    DEFAULT NULL,
    BatchEmail             varchar(1)     DEFAULT NULL,
    EmailAddress           varchar(250)   DEFAULT NULL,
    LastPurchaseOrderDate  date           DEFAULT NULL,
    LastPurchaseOrderNo    varchar(7)     DEFAULT NULL,
    SalesOrderNo           varchar(7)     DEFAULT NULL,
    RequisitorName         varchar(50)    DEFAULT NULL,
    RequisitorDepartment   varchar(30)    DEFAULT NULL,
    UDF_SHIPDATE           date           DEFAULT NULL,
    PRIMARY KEY (`PurchaseOrderNo`)
);
CREATE INDEX KEY0 on PO_PurchaseOrderHeader (PurchaseOrderNo);
CREATE INDEX KEY1 on PO_PurchaseOrderHeader (APDivisionNo, VendorNo, PurchaseOrderNo);
