CREATE TABLE PO_PurchaseOrderDetail
(
    PurchaseOrderNo              varchar(7) NOT NULL,
    LineKey                      varchar(6) NOT NULL,
    LineSeqNo                    varchar(14)    DEFAULT NULL,
    ItemCode                     varchar(30)    DEFAULT NULL,
    ExtendedDescriptionKey       varchar(10)    DEFAULT NULL,
    ItemType                     varchar(1)     DEFAULT NULL,
    ItemCodeDesc                 varchar(30)    DEFAULT NULL,
    UseTax                       varchar(1)     DEFAULT NULL,
    RequiredDate                 date           DEFAULT NULL,
    VendorPriceCode              varchar(4)     DEFAULT NULL,
    PurchasesAcctKey             varchar(9)     DEFAULT NULL,
    Valuation                    varchar(1)     DEFAULT NULL,
    UnitOfMeasure                varchar(4)     DEFAULT NULL,
    WarehouseCode                varchar(3)     DEFAULT NULL,
    ProductLine                  varchar(4)     DEFAULT NULL,
    MasterLineKey                varchar(6)     DEFAULT NULL,
    Reschedule                   varchar(1)     DEFAULT NULL,
    JobNo                        varchar(7)     DEFAULT NULL,
    CostCode                     varchar(9)     DEFAULT NULL,
    CostType                     varchar(1)     DEFAULT NULL,
    ReceiptOfGoodsUpdated        varchar(1)     DEFAULT NULL,
    WorkOrderNo                  varchar(7)     DEFAULT NULL,
    StepNo                       varchar(4)     DEFAULT NULL,
    SubStepPrefix                varchar(1)     DEFAULT NULL,
    SubStepSuffix                varchar(4)     DEFAULT NULL,
    WorkOrderType                varchar(1)     DEFAULT NULL,
    AllocateLandedCost           varchar(1)     DEFAULT NULL,
    VendorAliasItemNo            varchar(30)    DEFAULT NULL,
    TaxClass                     varchar(2)     DEFAULT NULL,
    CommentText                  TEXT           DEFAULT NULL,
    AssetAccount                 varchar(1)     DEFAULT NULL,
    AssetTemplate                varchar(25)    DEFAULT NULL,
    WeightReference              varchar(10)    DEFAULT NULL,
    Weight                       decimal(15, 6) DEFAULT NULL,
    QuantityOrdered              decimal(15, 6) DEFAULT NULL,
    QuantityReceived             decimal(15, 6) DEFAULT NULL,
    QuantityBackordered          decimal(15, 6) DEFAULT NULL,
    MasterOriginalQty            decimal(15, 6) DEFAULT NULL,
    MasterQtyBalance             decimal(15, 6) DEFAULT NULL,
    MasterQtyOrderedToDate       decimal(15, 6) DEFAULT NULL,
    QuantityInvoiced             decimal(15, 6) DEFAULT NULL,
    UnitCost                     decimal(15, 6) DEFAULT NULL,
    OriginalUnitCost             decimal(15, 6) DEFAULT NULL,
    ExtensionAmt                 decimal(11, 2) DEFAULT NULL,
    ReceivedAmt                  decimal(11, 2) DEFAULT NULL,
    InvoicedAmt                  decimal(11, 2) DEFAULT NULL,
    UnitOfMeasureConvFactor      decimal(11, 4) DEFAULT NULL,
    ReceivedAllocatedAmt         decimal(11, 2) DEFAULT NULL,
    InvoicedAllocatedAmt         decimal(11, 2) DEFAULT NULL,
    SalesOrderNo                 varchar(7)     DEFAULT NULL,
    CustomerPONo                 varchar(30)    DEFAULT NULL,
    PurchaseOrderHistoryDtlSeqNo varchar(14)    DEFAULT NULL,
    PRIMARY KEY (`PurchaseOrderNo`, `LineKey`)
);
CREATE INDEX KEY0 on PO_PurchaseOrderDetail (PurchaseOrderNo, LineKey);
CREATE INDEX KEY1 on PO_PurchaseOrderDetail (PurchaseOrderNo, LineSeqNo, LineKey);
CREATE INDEX KEY2 on PO_PurchaseOrderDetail (ExtendedDescriptionKey, PurchaseOrderNo, LineKey);
CREATE INDEX KEY3 on PO_PurchaseOrderDetail (ItemType, ItemCode, PurchaseOrderNo, LineKey);
CREATE INDEX KEY4 on PO_PurchaseOrderDetail (ItemCode, WarehouseCode, PurchaseOrderNo, LineKey);
