CREATE TABLE PR_DeductionCode
(
    DeductionCode                  varchar(6) NOT NULL,
    DeductionDesc                  varchar(30)    DEFAULT NULL,
    DeductionType                  varchar(1)     DEFAULT NULL,
    CalculationMethod              varchar(1)     DEFAULT NULL,
    StandardAmt                    decimal(12, 2) DEFAULT NULL,
    StandardRate                   decimal(9, 4)  DEFAULT NULL,
    StandardLimit                  decimal(10, 2) DEFAULT NULL,
    ApplyToW2Box                   varchar(2)     DEFAULT NULL,
    W2Box12Code                    varchar(2)     DEFAULT NULL,
    RetainResetAtEndOfYear         varchar(1)     DEFAULT NULL,
    EmployeePayRate                varchar(1)     DEFAULT NULL,
    DeductionCodeToUse             varchar(6)     DEFAULT NULL,
    EqualToEarningsCode1           varchar(6)     DEFAULT NULL,
    EqualToEarningsCode2           varchar(6)     DEFAULT NULL,
    EqualToEarningsCode3           varchar(6)     DEFAULT NULL,
    FrequencyPayPeriod1            varchar(1)     DEFAULT NULL,
    FrequencyPayPeriod2            varchar(1)     DEFAULT NULL,
    FrequencyPayPeriod3            varchar(1)     DEFAULT NULL,
    FrequencyPayPeriod4            varchar(1)     DEFAULT NULL,
    FrequencyPayPeriod5            varchar(1)     DEFAULT NULL,
    AutoApplyDeductionToEarnings   varchar(6)     DEFAULT NULL,
    DeductionAccrualAcctKey        varchar(9)     DEFAULT NULL,
    ContributionExpenseAcctKey     varchar(9)     DEFAULT NULL,
    BasedOnRegularEarnings         varchar(1)     DEFAULT NULL,
    BasedOnOvertimeEarnings        varchar(1)     DEFAULT NULL,
    BasedOnTimeOff1Earnings        varchar(1)     DEFAULT NULL,
    BasedOnTimeOff2Earnings        varchar(1)     DEFAULT NULL,
    BasedOnTimeOff3Earnings        varchar(1)     DEFAULT NULL,
    BasedOnMiscellaneousEarnings   varchar(1)     DEFAULT NULL,
    BasedOnExcludedFromTipCalcEarn varchar(1)     DEFAULT NULL,
    BasedOnFringeEarnings          varchar(1)     DEFAULT NULL,
    TaxRule                        varchar(11)    DEFAULT NULL,
    DateCreated                    date           DEFAULT NULL,
    TimeCreated                    varchar(8)     DEFAULT NULL,
    UserCreatedKey                 varchar(10)    DEFAULT NULL,
    DateUpdated                    date           DEFAULT NULL,
    TimeUpdated                    varchar(8)     DEFAULT NULL,
    UserUpdatedKey                 varchar(10)    DEFAULT NULL,
    CertifiedPayrollBenefitType    varchar(1)     DEFAULT NULL,
    PRIMARY KEY (`DeductionCode`)
);
CREATE INDEX KEY0 on PR_DeductionCode (DeductionCode);
