CREATE TABLE PR_Employee
(
    EmployeeKey                    varchar(32) NOT NULL,
    DepartmentNo                   varchar(2)     DEFAULT NULL,
    EmployeeNo                     varchar(7)     DEFAULT NULL,
    LastName                       varchar(40)    DEFAULT NULL,
    Suffix                         varchar(4)     DEFAULT NULL,
    FirstName                      varchar(25)    DEFAULT NULL,
    MiddleName                     varchar(25)    DEFAULT NULL,
    AddressLine1                   varchar(40)    DEFAULT NULL,
    AddressLine2                   varchar(40)    DEFAULT NULL,
    City                           varchar(30)    DEFAULT NULL,
    State                          varchar(2)     DEFAULT NULL,
    ZipCode                        varchar(10)    DEFAULT NULL,
    CountryCode                    varchar(3)     DEFAULT NULL,
    TelephoneNo1                   varchar(20)    DEFAULT NULL,
    TelephoneExt1                  varchar(6)     DEFAULT NULL,
    TelephoneType1                 varchar(1)     DEFAULT NULL,
    PrimaryTelephone1              varchar(1)     DEFAULT NULL,
    TelephoneNo2                   varchar(20)    DEFAULT NULL,
    TelephoneExt2                  varchar(6)     DEFAULT NULL,
    TelephoneType2                 varchar(1)     DEFAULT NULL,
    PrimaryTelephone2              varchar(1)     DEFAULT NULL,
    EmailAddress                   varchar(50)    DEFAULT NULL,
    SocialSecurityNo               varchar(9)     DEFAULT NULL,
    BirthDate                      date           DEFAULT NULL,
    DirectDeposit                  varchar(1)     DEFAULT NULL,
    JobTitle                       varchar(50)    DEFAULT NULL,
    FullTimePartTime               varchar(1)     DEFAULT NULL,
    SeasonalEmployee               varchar(1)     DEFAULT NULL,
    StatutoryEmployee              varchar(1)     DEFAULT NULL,
    EmployeeStatus                 varchar(1)     DEFAULT NULL,
    HireDate                       date           DEFAULT NULL,
    HireComment                    varchar(30)    DEFAULT NULL,
    ReviewDate                     date           DEFAULT NULL,
    ReviewComment                  varchar(30)    DEFAULT NULL,
    InactiveDate                   date           DEFAULT NULL,
    InactiveComment                varchar(30)    DEFAULT NULL,
    TerminationDate                date           DEFAULT NULL,
    TerminationComment             varchar(30)    DEFAULT NULL,
    RehireDate                     date           DEFAULT NULL,
    RehireComment                  varchar(30)    DEFAULT NULL,
    MaritalStatus                  varchar(1)     DEFAULT NULL,
    Gender                         varchar(1)     DEFAULT NULL,
    EthnicityRace                  varchar(1)     DEFAULT NULL,
    Veteran                        varchar(1)     DEFAULT NULL,
    VeteranSeparationServiceDate   date           DEFAULT NULL,
    SortField                      varchar(10)    DEFAULT NULL,
    Location                       varchar(10)    DEFAULT NULL,
    EmergencyContact1              varchar(30)    DEFAULT NULL,
    EmergencyTelephoneNo1          varchar(20)    DEFAULT NULL,
    EmergencyTelephoneExt1         varchar(6)     DEFAULT NULL,
    EmergencyTelephoneType1        varchar(1)     DEFAULT NULL,
    EmergencyRelationship1         varchar(30)    DEFAULT NULL,
    EmergencyContact2              varchar(30)    DEFAULT NULL,
    EmergencyTelephoneNo2          varchar(20)    DEFAULT NULL,
    EmergencyTelephoneExt2         varchar(6)     DEFAULT NULL,
    EmergencyTelephoneType2        varchar(1)     DEFAULT NULL,
    EmergencyRelationship2         varchar(30)    DEFAULT NULL,
    MedicalCoverage                varchar(1)     DEFAULT NULL,
    MedicalEffectiveDate           date           DEFAULT NULL,
    TimeOffCode                    varchar(6)     DEFAULT NULL,
    TimeOffEligibilityDate         date           DEFAULT NULL,
    TimeOffLastResetDate           date           DEFAULT NULL,
    DefaultTaxProfileCode          varchar(30)    DEFAULT NULL,
    WorkTaxStateCode               varchar(2)     DEFAULT NULL,
    WorkTaxLocationCode            varchar(30)    DEFAULT NULL,
    ResidenceTaxStateCode          varchar(2)     DEFAULT NULL,
    ResidenceTaxLocationCode       varchar(30)    DEFAULT NULL,
    SetupComplete                  varchar(1)     DEFAULT NULL,
    EmployeeCheckName              varchar(50)    DEFAULT NULL,
    LaborCode                      varchar(7)     DEFAULT NULL,
    PayCycle                       varchar(1)     DEFAULT NULL,
    PayMethod                      varchar(1)     DEFAULT NULL,
    ExemptFromOvertime             varchar(1)     DEFAULT NULL,
    MultipleAutomaticEarnings      varchar(1)     DEFAULT NULL,
    SummarizePayDtlOnStub          varchar(1)     DEFAULT NULL,
    EmployeePayRate1DateChanged    date           DEFAULT NULL,
    EmployeePayRate1ChangeComment  varchar(30)    DEFAULT NULL,
    EmployeePayRate2DateChanged    date           DEFAULT NULL,
    EmployeePayRate2ChangeComment  varchar(30)    DEFAULT NULL,
    EmployeePayRate3DateChanged    date           DEFAULT NULL,
    EmployeePayRate3ChangeComment  varchar(30)    DEFAULT NULL,
    EmployeePayRate4DateChanged    date           DEFAULT NULL,
    EmployeePayRate4ChangeComment  varchar(30)    DEFAULT NULL,
    EmployeePayRate5DateChanged    date           DEFAULT NULL,
    EmployeePayRate5ChangeComment  varchar(30)    DEFAULT NULL,
    EmployeePayRate6DateChanged    date           DEFAULT NULL,
    EmployeePayRate6ChangeComment  varchar(30)    DEFAULT NULL,
    EmployeePayRate7DateChanged    date           DEFAULT NULL,
    EmployeePayRate7ChangeComment  varchar(30)    DEFAULT NULL,
    EmployeePayRate8DateChanged    date           DEFAULT NULL,
    EmployeePayRate8ChangeComment  varchar(30)    DEFAULT NULL,
    EmployeePayRate9DateChanged    date           DEFAULT NULL,
    EmployeePayRate9ChangeComment  varchar(30)    DEFAULT NULL,
    TimeOff1CarryoverHours         decimal(6, 2)  DEFAULT NULL,
    TimeOff1AccruedHours           decimal(6, 2)  DEFAULT NULL,
    TimeOff1UsedHours              decimal(6, 2)  DEFAULT NULL,
    TimeOff1AnnualLimitHours       decimal(7, 2)  DEFAULT NULL,
    TimeOff2CarryoverHours         decimal(6, 2)  DEFAULT NULL,
    TimeOff2AccruedHours           decimal(6, 2)  DEFAULT NULL,
    TimeOff2UsedHours              decimal(6, 2)  DEFAULT NULL,
    TimeOff2AnnualLimitHours       decimal(7, 2)  DEFAULT NULL,
    TimeOff3CarryoverHours         decimal(6, 2)  DEFAULT NULL,
    TimeOff3AccruedHours           decimal(6, 2)  DEFAULT NULL,
    TimeOff3UsedHours              decimal(6, 2)  DEFAULT NULL,
    TimeOff3AnnualLimitHours       decimal(7, 2)  DEFAULT NULL,
    AutopayHours                   decimal(6, 2)  DEFAULT NULL,
    EmployeePayRate1               decimal(11, 3) DEFAULT NULL,
    EmployeePayRate2               decimal(11, 3) DEFAULT NULL,
    EmployeePayRate3               decimal(11, 3) DEFAULT NULL,
    EmployeePayRate4               decimal(11, 3) DEFAULT NULL,
    EmployeePayRate5               decimal(11, 3) DEFAULT NULL,
    EmployeePayRate6               decimal(11, 3) DEFAULT NULL,
    EmployeePayRate7               decimal(11, 3) DEFAULT NULL,
    EmployeePayRate8               decimal(11, 3) DEFAULT NULL,
    EmployeePayRate9               decimal(11, 3) DEFAULT NULL,
    EncryptedVals                  TEXT           DEFAULT NULL,
    SSNSort                        varchar(32)    DEFAULT NULL,
    DateCreated                    date           DEFAULT NULL,
    TimeCreated                    varchar(8)     DEFAULT NULL,
    UserCreatedKey                 varchar(10)    DEFAULT NULL,
    DateUpdated                    date           DEFAULT NULL,
    TimeUpdated                    varchar(8)     DEFAULT NULL,
    UserUpdatedKey                 varchar(10)    DEFAULT NULL,
    RetirementPlan                 varchar(1)     DEFAULT NULL,
    TimeTrackShiftCode             varchar(6)     DEFAULT NULL,
    TimeTrackBadgeNo               varchar(10)    DEFAULT NULL,
    TimeTrackPunchInOutPassword    varchar(33)    DEFAULT NULL,
    TimeTrackDfltCostCode          varchar(9)     DEFAULT NULL,
    TimeTrackDfltRegEarningsCode   varchar(6)     DEFAULT NULL,
    TimeTrackDfltOTEarningsCode    varchar(6)     DEFAULT NULL,
    TimeTrackDfltOtherEarningsCode varchar(6)     DEFAULT NULL,
    AddressLine3                   varchar(40)    DEFAULT NULL,
    GenderIdentity                 varchar(1)     DEFAULT NULL,
    EEOJobCategory                 varchar(1)     DEFAULT NULL,
    SelfServiceEnabled             varchar(1)     DEFAULT NULL,
    PRIMARY KEY (`EmployeeKey`)
);
CREATE INDEX KEY0 on PR_Employee (EmployeeKey);
CREATE INDEX KEY1 on PR_Employee (DepartmentNo, EmployeeNo);
CREATE INDEX KEY2 on PR_Employee (SortField, EmployeeKey);
CREATE INDEX KEY3 on PR_Employee (EmployeeNo, EmployeeKey);
CREATE INDEX KEY4 on PR_Employee (TimeTrackBadgeNo, EmployeeKey);
CREATE INDEX KEY5 on PR_Employee (TimeTrackShiftCode, EmployeeKey);
