CREATE TABLE PR_PayrollCycle
(
    BatchNo                      varchar(5) NOT NULL,
    PayCycle                     varchar(1)    DEFAULT NULL,
    PayPeriodStartingDate        date          DEFAULT NULL,
    PayPeriodEndingDate          date          DEFAULT NULL,
    CheckDate                    date          DEFAULT NULL,
    DeductionPeriod              varchar(1)    DEFAULT NULL,
    ManualTaxes                  varchar(1)    DEFAULT NULL,
    AutomaticDeductions          varchar(1)    DEFAULT NULL,
    PrintCheck                   varchar(1)    DEFAULT NULL,
    StandardEarningsCode         varchar(6)    DEFAULT NULL,
    StatusFlag                   varchar(1)    DEFAULT NULL,
    ChecksPrinted                varchar(1)    DEFAULT NULL,
    BankCode                     varchar(1)    DEFAULT NULL,
    CheckPrintingInProgress      varchar(1)    DEFAULT NULL,
    NextCheckNo                  varchar(10)   DEFAULT NULL,
    StartingCheckNo              varchar(10)   DEFAULT NULL,
    DirectDeposit                varchar(1)    DEFAULT NULL,
    DirectDepositEntriesExist    varchar(1)    DEFAULT NULL,
    DirectDepositEffectiveDate   date          DEFAULT NULL,
    DirectDepStubPrintingStarted varchar(1)    DEFAULT NULL,
    DirectDepositComment         varchar(10)   DEFAULT NULL,
    AccrualDate                  date          DEFAULT NULL,
    AutomaticEarnings            varchar(1)    DEFAULT NULL,
    DaysWorked                   decimal(4, 0) DEFAULT NULL,
    WeeksWorked                  decimal(3, 0) DEFAULT NULL,
    AccrualPercent               decimal(7, 2) DEFAULT NULL,
    DateCreated                  date          DEFAULT NULL,
    TimeCreated                  varchar(8)    DEFAULT NULL,
    UserCreatedkey               varchar(10)   DEFAULT NULL,
    DateUpdated                  date          DEFAULT NULL,
    TimeUpdated                  varchar(8)    DEFAULT NULL,
    UserUpdatedKey               varchar(10)   DEFAULT NULL,
    AllowAllPayCycles            varchar(1)    DEFAULT NULL,
    PRIMARY KEY (`BatchNo`)
);
CREATE INDEX KEY0 on PR_PayrollCycle (BatchNo);
