CREATE TABLE c2.SO_SalesOrderHeader
(
    SalesOrderNo                  varchar(7) NOT NULL,
    OrderDate                     date           DEFAULT NULL,
    OrderType                     varchar(1)     DEFAULT NULL,
    OrderStatus                   varchar(1)     DEFAULT NULL,
    MasterRepeatingOrderNo        varchar(7)     DEFAULT NULL,
    ShipExpireDate                date           DEFAULT NULL,
    ARDivisionNo                  varchar(2)     DEFAULT NULL,
    CustomerNo                    varchar(20)    DEFAULT NULL,
    BillToName                    varchar(50)    DEFAULT NULL,
    BillToAddress1                varchar(40)    DEFAULT NULL,
    BillToAddress2                varchar(40)    DEFAULT NULL,
    BillToAddress3                varchar(40)    DEFAULT NULL,
    BillToCity                    varchar(30)    DEFAULT NULL,
    BillToState                   varchar(2)     DEFAULT NULL,
    BillToZipCode                 varchar(10)    DEFAULT NULL,
    BillToCountryCode             varchar(3)     DEFAULT NULL,
    ShipToCode                    varchar(4)     DEFAULT NULL,
    ShipToName                    varchar(50)    DEFAULT NULL,
    ShipToAddress1                varchar(40)    DEFAULT NULL,
    ShipToAddress2                varchar(40)    DEFAULT NULL,
    ShipToAddress3                varchar(40)    DEFAULT NULL,
    ShipToCity                    varchar(30)    DEFAULT NULL,
    ShipToState                   varchar(2)     DEFAULT NULL,
    ShipToZipCode                 varchar(10)    DEFAULT NULL,
    ShipToCountryCode             varchar(3)     DEFAULT NULL,
    ShipVia                       varchar(15)    DEFAULT NULL,
    ShipZone                      varchar(5)     DEFAULT NULL,
    ShipZoneActual                varchar(5)     DEFAULT NULL,
    ShipWeight                    varchar(5)     DEFAULT NULL,
    CustomerPONo                  varchar(30)    DEFAULT NULL,
    FOB                           varchar(15)    DEFAULT NULL,
    WarehouseCode                 varchar(3)     DEFAULT NULL,
    ConfirmTo                     varchar(50)    DEFAULT NULL,
    Comment                       varchar(30)    DEFAULT NULL,
    TermsCode                     varchar(2)     DEFAULT NULL,
    TaxSchedule                   varchar(9)     DEFAULT NULL,
    TaxExemptNo                   varchar(15)    DEFAULT NULL,
    InvalidTaxCalc                varchar(1)     DEFAULT NULL,
    PrintSalesOrders              varchar(1)     DEFAULT NULL,
    PrintPickingSheets            varchar(1)     DEFAULT NULL,
    LastInvoiceOrderDate          date           DEFAULT NULL,
    LastInvoiceOrderNo            varchar(7)     DEFAULT NULL,
    CurrentInvoiceNo              varchar(7)     DEFAULT NULL,
    CheckNoForDeposit             varchar(10)    DEFAULT NULL,
    CycleCode                     varchar(2)     DEFAULT NULL,
    FaxNo                         varchar(20)    DEFAULT NULL,
    BatchFax                      varchar(1)     DEFAULT NULL,
    BatchEmail                    varchar(1)     DEFAULT NULL,
    EmailAddress                  varchar(250)   DEFAULT NULL,
    FreightCalculationMethod      varchar(1)     DEFAULT NULL,
    LotSerialLinesExist           varchar(1)     DEFAULT NULL,
    SalespersonDivisionNo         varchar(2)     DEFAULT NULL,
    SalespersonNo                 varchar(4)     DEFAULT NULL,
    SplitCommissions              varchar(1)     DEFAULT NULL,
    SalespersonDivisionNo2        varchar(2)     DEFAULT NULL,
    SalespersonNo2                varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo3        varchar(2)     DEFAULT NULL,
    SalespersonNo3                varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo4        varchar(2)     DEFAULT NULL,
    SalespersonNo4                varchar(4)     DEFAULT NULL,
    SalespersonDivisionNo5        varchar(2)     DEFAULT NULL,
    SalespersonNo5                varchar(4)     DEFAULT NULL,
    EBMUserType                   varchar(1)     DEFAULT NULL,
    EBMSubmissionType             varchar(1)     DEFAULT NULL,
    EBMUserIDSubmittingThisOrder  varchar(15)    DEFAULT NULL,
    PaymentType                   varchar(5)     DEFAULT NULL,
    OtherPaymentTypeRefNo         varchar(24)    DEFAULT NULL,
    CancelReasonCode              varchar(5)     DEFAULT NULL,
    PaymentTypeCategory           varchar(1)     DEFAULT NULL,
    RMANo                         varchar(7)     DEFAULT NULL,
    JobNo                         varchar(7)     DEFAULT NULL,
    ResidentialAddress            varchar(1)     DEFAULT NULL,
    TaxableSubjectToDiscount      decimal(12, 2) DEFAULT NULL,
    NonTaxableSubjectToDiscount   decimal(12, 2) DEFAULT NULL,
    TaxSubjToDiscPrcntOfTotSubjTo decimal(6, 2)  DEFAULT NULL,
    DiscountRate                  decimal(7, 3)  DEFAULT NULL,
    DiscountAmt                   decimal(11, 2) DEFAULT NULL,
    TaxableAmt                    decimal(12, 2) DEFAULT NULL,
    NonTaxableAmt                 decimal(12, 2) DEFAULT NULL,
    SalesTaxAmt                   decimal(11, 2) DEFAULT NULL,
    Weight                        decimal(11, 2) DEFAULT NULL,
    FreightAmt                    decimal(11, 2) DEFAULT NULL,
    DepositAmt                    decimal(12, 2) DEFAULT NULL,
    CommissionRate                decimal(8, 3)  DEFAULT NULL,
    SplitCommRate2                decimal(8, 3)  DEFAULT NULL,
    SplitCommRate3                decimal(8, 3)  DEFAULT NULL,
    SplitCommRate4                decimal(8, 3)  DEFAULT NULL,
    SplitCommRate5                decimal(8, 3)  DEFAULT NULL,
    NumberOfShippingLabels        decimal(3, 0)  DEFAULT NULL,
    LastNoOfShippingLabels        decimal(3, 0)  DEFAULT NULL,
    DateCreated                   date           DEFAULT NULL,
    TimeCreated                   varchar(8)     DEFAULT NULL,
    UserCreatedKey                varchar(10)    DEFAULT NULL,
    DateUpdated                   date           DEFAULT NULL,
    TimeUpdated                   varchar(8)     DEFAULT NULL,
    UserUpdatedKey                varchar(10)    DEFAULT NULL,
    UDF_CANCEL_DATE               date           DEFAULT NULL,
    UDF_MFP_NAME                  varchar(25)    DEFAULT NULL,
    UDF_MFP_NUMBER                decimal(7, 0)  DEFAULT NULL,
    UDF_PROGRAMCOUNT              varchar(10)    DEFAULT NULL,
    UDF_PROGRAMID                 varchar(10)    DEFAULT NULL,
    UDF_COUNTRY                   varchar(3)     DEFAULT NULL,
    UDF_IMPRINTED                 varchar(1)     DEFAULT NULL,
    UDF_CREATED_KEY               varchar(10)    DEFAULT NULL,
    UDF_DATE_CREATED_KEY          date           DEFAULT NULL,
    UDF_DATE_UPDATED_KEY          date           DEFAULT NULL,
    UDF_UPDATED_KEY               varchar(10)    DEFAULT NULL,
    CRMUserID                     varchar(11)    DEFAULT NULL,
    CRMPersonID                   varchar(11)    DEFAULT NULL,
    CRMOpportunityID              varchar(11)    DEFAULT NULL,
    CRMCompanyID                  varchar(11)    DEFAULT NULL,
    CRMProspectID                 varchar(11)    DEFAULT NULL,
    SalesOrderPrinted             varchar(1)     DEFAULT NULL,
    PickingSheetPrinted           varchar(1)     DEFAULT NULL,
    BillToDivisionNo              varchar(2)     DEFAULT NULL,
    BillToCustomerNo              varchar(20)    DEFAULT NULL,
    PromotedDate                  date           DEFAULT NULL,
    D546_CreditCardMagneticStrip  varchar(120)   DEFAULT NULL,
    D546_SendEmail                varchar(1)     DEFAULT NULL,
    UDF_BAK_02                    varchar(2)     DEFAULT NULL,
    UDF_BT                        varchar(20)    DEFAULT NULL,
    UDF_CUST_ORD_NO               varchar(30)    DEFAULT NULL,
    UDF_DC                        varchar(4)     DEFAULT NULL,
    UDF_DEPT                      varchar(15)    DEFAULT NULL,
    UDF_DEPT_NAME                 varchar(30)    DEFAULT NULL,
    UDF_DIV_REGION                varchar(30)    DEFAULT NULL,
    UDF_LETTER_CR                 varchar(30)    DEFAULT NULL,
    UDF_MR                        varchar(30)    DEFAULT NULL,
    UDF_PROMO_DEAL                varchar(30)    DEFAULT NULL,
    UDF_REQUESTED_DELIVERY        date           DEFAULT NULL,
    UDF_ST                        varchar(20)    DEFAULT NULL,
    UDF_ST_PER01                  varchar(3)     DEFAULT NULL,
    UDF_ST_PER02                  varchar(35)    DEFAULT NULL,
    UDF_ST_PER04_TE               varchar(15)    DEFAULT NULL,
    UDF_ST_PER06_EM               varchar(50)    DEFAULT NULL,
    UDF_ST_PER08_FX               varchar(15)    DEFAULT NULL,
    UDF_VENDOR_NO                 varchar(30)    DEFAULT NULL,
    UDF_Z7                        varchar(20)    DEFAULT NULL,
    PayBalance                    varchar(1)     DEFAULT NULL,
    PRIMARY KEY (SalesOrderNo)
)
