CREATE TABLE SO_ShipToAddress
(
    ARDivisionNo          varchar(2)  NOT NULL,
    CustomerNo            varchar(20) NOT NULL,
    ShipToCode            varchar(4)  NOT NULL,
    ShipToName            varchar(50) DEFAULT NULL,
    ShipToAddress1        varchar(40) DEFAULT NULL,
    ShipToAddress2        varchar(40) DEFAULT NULL,
    ShipToAddress3        varchar(40) DEFAULT NULL,
    ShipToCity            varchar(30) DEFAULT NULL,
    ShipToState           varchar(2)  DEFAULT NULL,
    ShipToZipCode         varchar(10) DEFAULT NULL,
    ShipToCountryCode     varchar(3)  DEFAULT NULL,
    TelephoneNo           varchar(20) DEFAULT NULL,
    TelephoneExt          varchar(6)  DEFAULT NULL,
    FaxNo                 varchar(20) DEFAULT NULL,
    BatchFax              varchar(1)  DEFAULT NULL,
    BatchEmail            varchar(1)  DEFAULT NULL,
    EmailAddress          varchar(50) DEFAULT NULL,
    ContactCode           varchar(10) DEFAULT NULL,
    SalespersonDivisionNo varchar(2)  DEFAULT NULL,
    SalespersonNo         varchar(4)  DEFAULT NULL,
    WarehouseCode         varchar(3)  DEFAULT NULL,
    TaxSchedule           varchar(9)  DEFAULT NULL,
    ResidentialAddress    varchar(1)  DEFAULT NULL,
    DateCreated           date        DEFAULT NULL,
    TimeCreated           varchar(8)  DEFAULT NULL,
    UserCreatedKey        varchar(10) DEFAULT NULL,
    DateUpdated           date        DEFAULT NULL,
    TimeUpdated           varchar(8)  DEFAULT NULL,
    UserUpdatedKey        varchar(10) DEFAULT NULL,
    UDF_RESELLER          varchar(1)  DEFAULT NULL,
    ShipVia               varchar(15) DEFAULT NULL,
    UDF_DC                varchar(4)  DEFAULT NULL,
    TelephoneType         varchar(1)  DEFAULT NULL,
    EncryptedVals         TEXT        DEFAULT NULL,
    PRIMARY KEY (`ARDivisionNo`, `CustomerNo`, `ShipToCode`)
)
