CREATE TABLE WO1_WorkOrderMaster (
                                     WorkOrder char(7) NOT NULL,
                                     ItemBillDescription char(30) DEFAULT NULL,
                                     ItemUM char(4) DEFAULT NULL,
                                     BillRevision char(3) DEFAULT NULL,
                                     BillOptions char(18) DEFAULT NULL,
                                     EffectiveDate date DEFAULT NULL,
                                     RoutingNumber char(20) DEFAULT NULL,
                                     IssueMethod char(1) DEFAULT NULL,
                                     PrntPickList char(1) DEFAULT NULL,
                                     UserDefinedField1 char(10) DEFAULT NULL,
                                     UserDefinedField2 char(10) DEFAULT NULL,
                                     UserDefinedField3 char(10) DEFAULT NULL,
                                     UserDefinedField4 char(10) DEFAULT NULL,
                                     PlannerCode char(3) DEFAULT NULL,
                                     CopyFromTemplate char(7) DEFAULT NULL,
                                     PrntLabels char(1) DEFAULT NULL,
                                     ExplodeSubassemblies char(1) DEFAULT NULL,
                                     CostCmplMthd char(1) DEFAULT NULL,
                                     AutoIssueMatlTran char(1) DEFAULT NULL,
                                     AutoGenLabTran char(1) DEFAULT NULL,
                                     AutoGenOutsProcTran char(1) DEFAULT NULL,
                                     DateClosed date DEFAULT NULL,
                                     MakeFor char(1) DEFAULT NULL,
                                     MakeForOrderNumber char(7) DEFAULT NULL,
                                     SOLineIndex char(6) DEFAULT NULL,
                                     ParentWhse char(3) DEFAULT NULL,
                                     DefaultComponentWhse char(3) DEFAULT NULL,
                                     Status char(1) DEFAULT NULL,
                                     WODate date DEFAULT NULL,
                                     WODueDate date DEFAULT NULL,
                                     SchedRelDate date DEFAULT NULL,
                                     ActualProdStartDate date DEFAULT NULL,
                                     LastActivityDate date DEFAULT NULL,
                                     LastReschedDate date DEFAULT NULL,
                                     PriorDueDate date DEFAULT NULL,
                                     UserWhoLastResched char(3) DEFAULT NULL,
                                     OnHold char(1) DEFAULT NULL,
                                     StatusComment char(30) DEFAULT NULL,
                                     TravelerPrinted char(1) DEFAULT NULL,
                                     LastStepComplete char(4) DEFAULT NULL,
                                     SubstepPrefix char(1) DEFAULT NULL,
                                     SubstepSuffix char(4) DEFAULT NULL,
                                     CustomerDivision char(2) DEFAULT NULL,
                                     SOCustNumber char(20) DEFAULT NULL,
                                     ItemBillNumber varchar(30) DEFAULT NULL,
                                     LinkToFirstDetailRecord decimal(11,0) DEFAULT NULL,
                                     UMConversion decimal(15,4) DEFAULT NULL,
                                     QtyOrdered decimal(15,4) DEFAULT NULL,
                                     YieldPercentage decimal(15,4) DEFAULT NULL,
                                     QtyPlanned decimal(15,4) DEFAULT NULL,
                                     QtyComplete decimal(15,4) DEFAULT NULL,
                                     QtyTransferred decimal(15,4) DEFAULT NULL,
                                     QtyScrapped decimal(15,4) DEFAULT NULL,
                                     CalcLeadTime decimal(11,0) DEFAULT NULL,
                                     QtyCompletedToday decimal(15,4) DEFAULT NULL,
                                     StdLaborCost decimal(15,4) DEFAULT NULL,
                                     ActualLaborCost decimal(15,4) DEFAULT NULL,
                                     StdMaterialCost decimal(15,4) DEFAULT NULL,
                                     ActualMaterialCost decimal(15,4) DEFAULT NULL,
                                     StdOutsideProcessCost decimal(15,4) DEFAULT NULL,
                                     ActualOutsideProcessCost decimal(15,4) DEFAULT NULL,
                                     StdFixedOverheadCost decimal(15,4) DEFAULT NULL,
                                     ActualFixedOverheadCost decimal(15,4) DEFAULT NULL,
                                     StdVariableOverheadCost decimal(15,4) DEFAULT NULL,
                                     ActualVariableOvhdCost decimal(15,4) DEFAULT NULL,
                                     PRIMARY KEY (`WorkOrder`)
);
CREATE INDEX KEY0 on WO1_WorkOrderMaster (WorkOrder);
CREATE INDEX KEY1 on WO1_WorkOrderMaster (ItemBillDescription, WorkOrder);
CREATE INDEX KEY2 on WO1_WorkOrderMaster (ItemBillNumber, WorkOrder);
CREATE INDEX KEY3 on WO1_WorkOrderMaster (UserDefinedField1, WorkOrder);
CREATE INDEX KEY4 on WO1_WorkOrderMaster (UserDefinedField2, WorkOrder);
CREATE INDEX KEY5 on WO1_WorkOrderMaster (UserDefinedField3, WorkOrder);
CREATE INDEX KEY6 on WO1_WorkOrderMaster (UserDefinedField4, WorkOrder);
