CREATE TABLE WO1_WorkOrderMaster
(
    WorkOrder                CHAR NOT NULL,
    ItemBillDescription      CHAR           DEFAULT NULL,
    ItemUM                   CHAR           DEFAULT NULL,
    BillRevision             CHAR           DEFAULT NULL,
    BillOptions              CHAR           DEFAULT NULL,
    EffectiveDate            date           DEFAULT NULL,
    RoutingNumber            CHAR           DEFAULT NULL,
    IssueMethod              CHAR           DEFAULT NULL,
    PrntPickList             CHAR           DEFAULT NULL,
    UserDefinedField1        CHAR           DEFAULT NULL,
    UserDefinedField2        CHAR           DEFAULT NULL,
    UserDefinedField3        CHAR           DEFAULT NULL,
    UserDefinedField4        CHAR           DEFAULT NULL,
    PlannerCode              CHAR           DEFAULT NULL,
    CopyFromTemplate         CHAR           DEFAULT NULL,
    PrntLabels               CHAR           DEFAULT NULL,
    ExplodeSubassemblies     CHAR           DEFAULT NULL,
    CostCmplMthd             CHAR           DEFAULT NULL,
    AutoIssueMatlTran        CHAR           DEFAULT NULL,
    AutoGenLabTran           CHAR           DEFAULT NULL,
    AutoGenOutsProcTran      CHAR           DEFAULT NULL,
    DateClosed               date           DEFAULT NULL,
    MakeFor                  CHAR           DEFAULT NULL,
    MakeForOrderNumber       CHAR           DEFAULT NULL,
    SOLineIndex              CHAR           DEFAULT NULL,
    ParentWhse               CHAR           DEFAULT NULL,
    DefaultComponentWhse     CHAR           DEFAULT NULL,
    Status                   CHAR           DEFAULT NULL,
    WODate                   date           DEFAULT NULL,
    WODueDate                date           DEFAULT NULL,
    SchedRelDate             date           DEFAULT NULL,
    ActualProdStartDate      date           DEFAULT NULL,
    LastActivityDate         date           DEFAULT NULL,
    LastReschedDate          date           DEFAULT NULL,
    PriorDueDate             date           DEFAULT NULL,
    UserWhoLastResched       CHAR           DEFAULT NULL,
    OnHold                   CHAR           DEFAULT NULL,
    StatusComment            CHAR           DEFAULT NULL,
    TravelerPrinted          CHAR           DEFAULT NULL,
    LastStepComplete         CHAR           DEFAULT NULL,
    SubstepPrefix            CHAR           DEFAULT NULL,
    SubstepSuffix            CHAR           DEFAULT NULL,
    CustomerDivision         CHAR           DEFAULT NULL,
    SOCustNumber             CHAR           DEFAULT NULL,
    ItemBillNumber           varchar(30)    DEFAULT NULL,
    LinkToFirstDetailRecord  decimal(11, 0) DEFAULT NULL,
    UMConversion             decimal(15, 4) DEFAULT NULL,
    QtyOrdered               decimal(15, 4) DEFAULT NULL,
    YieldPercentage          decimal(15, 4) DEFAULT NULL,
    QtyPlanned               decimal(15, 4) DEFAULT NULL,
    QtyComplete              decimal(15, 4) DEFAULT NULL,
    QtyTransferred           decimal(15, 4) DEFAULT NULL,
    QtyScrapped              decimal(15, 4) DEFAULT NULL,
    CalcLeadTime             decimal(11, 0) DEFAULT NULL,
    QtyCompletedToday        decimal(15, 4) DEFAULT NULL,
    StdLaborCost             decimal(15, 4) DEFAULT NULL,
    ActualLaborCost          decimal(15, 4) DEFAULT NULL,
    StdMaterialCost          decimal(15, 4) DEFAULT NULL,
    ActualMaterialCost       decimal(15, 4) DEFAULT NULL,
    StdOutsideProcessCost    decimal(15, 4) DEFAULT NULL,
    ActualOutsideProcessCost decimal(15, 4) DEFAULT NULL,
    StdFixedOverheadCost     decimal(15, 4) DEFAULT NULL,
    ActualFixedOverheadCost  decimal(15, 4) DEFAULT NULL,
    StdVariableOverheadCost  decimal(15, 4) DEFAULT NULL,
    ActualVariableOvhdCost   decimal(15, 4) DEFAULT NULL,
    PRIMARY KEY (`WorkOrder`)
);
CREATE INDEX KEY0 on WO1_WorkOrderMaster (WorkOrder);
CREATE INDEX KEY1 on WO1_WorkOrderMaster (ItemBillDescription, WorkOrder);
CREATE INDEX KEY2 on WO1_WorkOrderMaster (ItemBillNumber, WorkOrder);
CREATE INDEX KEY3 on WO1_WorkOrderMaster (UserDefinedField1, WorkOrder);
CREATE INDEX KEY4 on WO1_WorkOrderMaster (UserDefinedField2, WorkOrder);
CREATE INDEX KEY5 on WO1_WorkOrderMaster (UserDefinedField3, WorkOrder);
CREATE INDEX KEY6 on WO1_WorkOrderMaster (UserDefinedField4, WorkOrder);
